Feature/header - Implement header according to UI specifications
ms-club-sliit/minihackathon-2024 pull request #12
Opened 2024-07-09 13:00 UTC by ramindu-Nimex

![full screen](https://github.com/ms-club-sliit/minihackathon-2024/assets/117975788/97a34d91-1eab-458b-ad0b-93e7be24ebd9)
![I-pad-mini](https://github.com/ms-club-sliit/minihackathon-2024/assets/117975788/68295087-fb59-4fa4-8863-667f6a8b5432)
![I-phone 14 Pro max](https://github.com/ms-club-sliit/minihackathon-2024/assets/117975788/11075133-3e70-4ac7-8108-ce1a5b9e4aa2)
![I-phone se](https://github.com/ms-club-sliit/minihackathon-2024/assets/117975788/e0c83873-9a78-44a9-913e-a96194ba9b9e)

2024-07-10 17:45 UTC, sathninduk commented on public/Facebook.png
Reorganize and refactor the file path (ex: public -> images -> logos)

2024-07-11 01:43 UTC, sathninduk requested changes

2024-07-11 06:38 UTC, Randula98 requested changes

2024-07-11 06:38 UTC, Randula98 commented on components/Header/index.jsx
> +                      className="text-lg font-semibold"
When hovering the text element, the cursor should be a pointer. Use tailwindcss inline styles to add that.

2024-07-11 06:38 UTC, Randula98 commented on components/Header/index.jsx
> +                <Image
When hovering the text element, the cursor should be a pointer. Use tailwindcss inline styles to add that.

2024-07-11 06:38 UTC, Randula98 commented on components/Header/index.jsx
> +import logomain from "../../public/images/logos/logomain.png";
Please review on image import syntax on next.js

2024-07-11 06:38 UTC, Randula98 commented on components/Header/index.jsx
> +  { src: Facebook, alt: "Facebook", link: "/" },
for example. 
/images/logos/Facebook.png

change the rest as nessasary

2024-07-11 07:28 UTC, Randula98 approved these changes
LGTM

2024-07-11 12:56 UTC, sathninduk approved these changes
LGTM

2024-07-11 13:02 UTC, merged